// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohkdlzzatzysxagobwsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oa2RsenphdHp5c3hhZ29id3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTAwMjMsImV4cCI6MjA2ODE2NjAyM30.G7uoKuZye9FLT8x45n2xZ-0hJ-lx12iu9RgmkUwvW-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});